Uncomment models in communication app
We're not able to get production to migrate due to this error:

ValueError: The field files.File.issues was declared with a lazy
    reference to 'communication.issue', but app 'communication' isn't
    installed.
The field files.FileIssue.issue was declared with a lazy reference to
    'communication.issue', but app 'communication' isn't installed.

Uncommenting models to see if it works.